### ISSUE TITLE
Potential bug found via `eslint-plugin-json-files` tests

### ISSUE THREAD

**Issue by benmccann** [SuperchupuDev/tinyglobby#6]
I tried to switch over `eslint-plugin-json-files`, but the tests failed. 

My branch is here: https://github.com/benmccann/eslint-plugin-json-files/tree/tinyglobby

The tests fail when running `npm install && npm test`, but pass on `main`

**Comment by benmccann** [comment]
The failing output looks like:
```
  3 failing

  1) ensure-workspaces
       valid
         module.exports = { "workspaces": ["tests/fixtures/workspaces/*/bar"] }:

      AssertionError [ERR_ASSERTION]: Should have no errors but had 1: [
  {
    ruleId: 'ensure-workspaces',
    severity: 1,
    message: 'workspace path/glob does not match any workspaces with a package.json.',
    line: 1,
    column: 35,
    nodeType: 'Literal',
    endLine: 1,
    endColumn: 68
  }
]
      + expected - actual

      -1
      +0
      
      at testValidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:899:20)
      at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:1181:33)
      at process.processImmediate (node:internal/timers:478:21)

  2) ensure-workspaces
       valid
         module.exports = { "workspaces": ["tests/fixtures/workspaces/*/bar"] }:

      AssertionError [ERR_ASSERTION]: Should have no errors but had 1: [
  {
    ruleId: 'ensure-workspaces',
    severity: 1,
    message: 'workspace path/glob does not match any workspaces with a package.json.',
    line: 1,
    column: 35,
    nodeType: 'Literal',
    endLine: 1,
    endColumn: 68
  }
]
      + expected - actual

      -1
      +0
      
      at testValidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:899:20)
      at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:1181:33)
      at process.processImmediate (node:internal/timers:478:21)

  3) ensure-workspaces
       valid
         module.exports = { "workspaces": { "packages": ["tests/fixtures/workspaces/*/bar"] } }:

      AssertionError [ERR_ASSERTION]: Should have no errors but had 1: [
  {
    ruleId: 'ensure-workspaces',
    severity: 1,
    message: 'workspace path/glob does not match any workspaces with a package.json.',
    line: 1,
    column: 49,
    nodeType: 'Literal',
    endLine: 1,
    endColumn: 82
  }
]
      + expected - actual

      -1
      +0
      
      at testValidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:899:20)
      at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:1181:33)
      at process.processImmediate (node:internal/timers:478:21)
```

**Comment by SuperchupuDev** [comment]
can you test again in 0.2.0?

**Comment by benmccann** [comment]
fixed!
